### ISSUE TITLE
`as_of` can't handle Date-type input

### ISSUE THREAD

**Issue by dshemetov** [cmu-delphi/epidatr#194] opened 2023-10-06 01:46 UTC
```R
r$> forecast_due_date = as.Date("2021-10-19")

r$> epidatr::pub_covidcast(
          "hhs",
          "confirmed_admissions_influenza_1d",
          "state",
          "day",
          "*",
          epirange(forecast_due_date - 20L, forecast_due_date),
          as_of = forecast_due_date
        )
Error in charToDate(x) : 
  character string is not in a standard unambiguous format

r$> epidatr::pub_covidcast(
          "hhs",
          "confirmed_admissions_influenza_1d",
          "state",
          "day",
          "*",
          epirange(forecast_due_date - 20L, forecast_due_date),
          as_of = "2021-10-19"
        )
# A tibble: 1,080 × 15
...
```

**Comment by dsweber2** [comment] 2023-10-06 18:10
pretty sure this is a dupe of #192, he mentions length 1 vectors as well

**Comment by dshemetov** [comment] 2023-10-06 18:15
Seems right, but let's keep this open so we make sure we address the example above with whatever fix we implement

**Comment by nmdefries** [comment] 2023-11-30 19:58
Closed by https://github.com/cmu-delphi/epidatr/pull/224

**Closed by nmdefries** 2023-11-30 19:58 UTC
Labels: bug
