### ISSUE TITLE
Package evaluation & first pass documentation

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/epidatr#13] opened 2021-09-22 15:39 UTC
The goal of this task is to better understand whether this package does what we need it to, and permit other Delphi members to understand the same without having to read the source.

Delphi blog posts that include plots also include the code used to produce those plots. Reproduce as many of the plots as you can from the following blog posts, using this package instead of `covidcastR`/`covidcast`. 

* [Home for the Holidays: surveys indicators](https://delphi.cmu.edu/blog/2021/02/02/home-for-the-holidays-the-impact-of-us-holidays-on-social-behaviors-and-preventative-measures/)
* [Syndromic outpatient indicator from claims](https://delphi.cmu.edu/blog/2020/11/05/a-syndromic-covid-19-indicator-based-on-insurance-claims-of-outpatient-visits/) 

Use your newly acquired knowledge to repair the Roxygen docs so that they run successfully, and flesh out [the package documentation](https://github.com/cmu-delphi/delphi-epidata-r/tree/dev/vignettes) with the basics.

**Comment by dshemetov** [comment] 2022-03-18 22:15
@krivard @ryantibs I went through the feature list document and marked what has been implemented, what is not, what is possibly out of scope, and what is not working correctly (as per the latest action task list from September in the [PRD document](https://docs.google.com/document/d/1yhrQz5mdFnU9WJypFmDnkGhUOMbLWIpIU3RXcYc444w/edit#)).

## Feature List

[Feature list doc here](https://docs.google.com/spreadsheets/d/190HH854Yij4kccnWmVDjjeaSihiQiIB0ar2o8BvNyk4/edit#gid=185106297).

- [x] Retrieve metadata from non-covidcast signals
```r
r$> meta() %>% fetch_classic
$epidata
                                                                                                                    delphi
1 201541, 201441, 201441, 201441, 201542, 201619, 201519, 202019, 201519, 201949, 31, 32, 177, 32, 123, af, eb, ec, sp, st
                      fluview                twitter               wiki
1 202210, 2022-03-18, 1528877 2020-12-07, 49, 142774 2021-03-19, 156143

$message
[1] "success"

$result
[1] 1

# The following are available with an auth token
r$> pvt_meta_afhsb(auth)
r$> pvt_meta_norostat(auth)

r$> fluview_meta() %>% fetch_tbl
Warning: 1 parsing failure.
row          col         expected actual         file
  1 latest_issue date like %Y%m%d 202210 literal data

# A tibble: 1 x 3
  latest_update latest_issue table_rows
  <chr>         <date>            <int>
1 2022-03-18    NA              1528877
```
- [x] Retrieve metadata from covidcast signals
```r
r$> covidcast_meta() %>% fetch_tbl()
Warning: 39 parsing failures.
 row       col         expected actual         file
2133 min_time  date like %Y%m%d 202005 literal data
2133 max_time  date like %Y%m%d 202209 literal data
2133 max_issue date like %Y%m%d 202211 literal data
2134 min_time  date like %Y%m%d 202005 literal data
2134 max_time  date like %Y%m%d 202209 literal data
.... ......... ................ ...... ............
See problems(...) for more details.

# A tibble: 2,409 x 15
   data_source signal time_type geo_type min_time   max_time   num_locations min_value max_value mean_value stdev_value
   <chr>       <chr>  <ord>     <chr>    <date>     <date>             <int>     <dbl>     <dbl>      <dbl>       <dbl>
 1 chng        smoot… day       county   2020-02-01 2022-03-12          3114 0.000933      99.9       2.74        4.40 
 2 chng        smoot… day       hhs      2020-02-01 2022-03-12            10 0.00620       20.8       3.24        2.82 
 3 chng        smoot… day       hrr      2020-02-01 2022-03-12           306 0.00103       50.8       3.01        3.14 
 4 chng        smoot… day       msa      2020-02-01 2022-03-12           392 0.000766      50.9       2.71        2.94 
 5 chng        smoot… day       nation   2020-02-01 2022-03-12             1 0.0155        12.1       3.55        2.54 
 6 chng        smoot… day       state    2020-02-01 2022-03-12            55 0.00133       33.2       2.91        2.90 
 7 chng        smoot… day       county   2020-02-01 2022-03-12          3113 0.000732      99.7       0.935       1.46 
 8 chng        smoot… day       hhs      2020-02-01 2022-03-12            10 0.0000994      6.62      0.847       0.901
 9 chng        smoot… day       hrr      2020-02-01 2022-03-12           306 0.000438      11.9       0.891       1.07 
10 chng        smoot… day       msa      2020-02-01 2022-03-12           392 0.000362      14.3       0.845       1.09 
# … with 2,399 more rows, and 4 more variables: last_update <int>, max_issue <date>, min_lag <int>, max_lag <int>
```
- [x] Retrieve as_of a certain date (where supported)
```r
r$> epicall <- covidcast("fb-survey", "smoothed_cli", "day", "nation", epirange(20210405, 20210410), "us", as_of = 20210409)

r$> epicall %>% fetch_tbl
# A tibble: 4 x 15
  geo_value signal source geo_type time_type time_value direction issue        lag missing_value missing_stderr
  <chr>     <chr>  <chr>  <ord>    <ord>     <date>         <dbl> <date>     <int>         <int>          <int>
1 us        smoot… fb-su… nation   day       2021-04-05        NA 2021-04-09     4             0              0
2 us        smoot… fb-su… nation   day       2021-04-06        NA 2021-04-09     3             0              0
3 us        smoot… fb-su… nation   day       2021-04-07        NA 2021-04-09     2             0              0
4 us        smoot… fb-su… nation   day       2021-04-08        NA 2021-04-09     1             0              0
# … with 4 more variables: missing_sample_size <int>, value <dbl>, stderr <dbl>, sample_size <dbl>

```
- [x] Retrieve most recent (latest issue) data  (where supported)
	- By default, a call to the API retrieves latest issue data.
- [x] Retrieve given a certain lag  (where supported)
```r
r$> epicall <- covidcast("fb-survey", "smoothed_cli", "day", "nation", epirange(20210405, 20210410), "us", lag = 2)

r$> epicall %>% fetch_tbl
# A tibble: 6 x 15
  geo_value signal source geo_type time_type time_value direction issue        lag missing_value missing_stderr
  <chr>     <chr>  <chr>  <ord>    <ord>     <date>         <dbl> <date>     <int>         <int>          <int>
1 us        smoot… fb-su… nation   day       2021-04-05        NA 2021-04-07     2             0              0
2 us        smoot… fb-su… nation   day       2021-04-06        NA 2021-04-08     2             0              0
3 us        smoot… fb-su… nation   day       2021-04-07        NA 2021-04-09     2             0              0
4 us        smoot… fb-su… nation   day       2021-04-08        NA 2021-04-10     2             0              0
5 us        smoot… fb-su… nation   day       2021-04-09        NA 2021-04-11     2             0              0
6 us        smoot… fb-su… nation   day       2021-04-10        NA 2021-04-12     2             0              0
# … with 4 more variables: missing_sample_size <int>, value <dbl>, stderr <dbl>, sample_size <dbl>
```
- [ ] Retrive as_of a range of time values  (where supported)
	- Implemented, but bugged?
```r
# Using a single as_of value works
r$> epicall <- covidcast("jhu-csse", "deaths_incidence_prop", "day", "nation", epirange(20211001, 20211010), "us", as_of = 2021
    1020)

r$> epicall %>% fetch_tbl
# A tibble: 10 x 15
   geo_value signal source geo_type time_type time_value direction issue        lag missing_value missing_stderr
   <chr>     <chr>  <chr>  <ord>    <ord>     <date>         <dbl> <date>     <int>         <int>          <int>
 1 us        death… jhu-c… nation   day       2021-10-01        NA 2021-10-20    19             0              0
 2 us        death… jhu-c… nation   day       2021-10-02        NA 2021-10-19    17             0              0
 3 us        death… jhu-c… nation   day       2021-10-03        NA 2021-10-20    17             0              0
 4 us        death… jhu-c… nation   day       2021-10-04        NA 2021-10-20    16             0              0
 5 us        death… jhu-c… nation   day       2021-10-05        NA 2021-10-20    15             0              0
 6 us        death… jhu-c… nation   day       2021-10-06        NA 2021-10-20    14             0              0
 7 us        death… jhu-c… nation   day       2021-10-07        NA 2021-10-20    13             0              0
 8 us        death… jhu-c… nation   day       2021-10-08        NA 2021-10-20    12             0              0
 9 us        death… jhu-c… nation   day       2021-10-09        NA 2021-10-19    10             0              0
10 us        death… jhu-c… nation   day       2021-10-10        NA 2021-10-20    10             0              0
# … with 4 more variables: missing_sample_size <int>, value <dbl>, stderr <dbl>, sample_size <dbl>

# But using a range seems to default to the latest as_of
r$> epicall <- covidcast("jhu-csse", "deaths_incidence_prop", "day", "nation", epirange(20211001, 20211010), "us", as_of = epir
    ange(20211010, 20211020))

r$> epicall %>% fetch_tbl
# A tibble: 10 x 15
   geo_value signal source geo_type time_type time_value direction issue        lag missing_value missing_stderr
   <chr>     <chr>  <chr>  <ord>    <ord>     <date>         <dbl> <date>     <int>         <int>          <int>
 1 us        death… jhu-c… nation   day       2021-10-01        NA 2022-03-18   168             0              5
 2 us        death… jhu-c… nation   day       2021-10-02        NA 2022-03-11   160             0              5
 3 us        death… jhu-c… nation   day       2021-10-03        NA 2022-03-18   166             0              5
 4 us        death… jhu-c… nation   day       2021-10-04        NA 2022-03-11   158             0              5
 5 us        death… jhu-c… nation   day       2021-10-05        NA 2022-03-11   157             0              5
 6 us        death… jhu-c… nation   day       2021-10-06        NA 2022-03-11   156             0              5
 7 us        death… jhu-c… nation   day       2021-10-07        NA 2022-03-11   155             0              5
 8 us        death… jhu-c… nation   day       2021-10-08        NA 2022-03-11   154             0              5
 9 us        death… jhu-c… nation   day       2021-10-09        NA 2022-03-11   153             0              5
10 us        death… jhu-c… nation   day       2021-10-10        NA 2022-03-18   159             0              5
# … with 4 more variables: missing_sample_size <int>, value <dbl>, stderr <dbl>, sample_size <dbl>
```
- [x] Authenticate via API key, passed in each call
	- Seems possible.
```r
pvt_afhsb(auth)
pvt_cdc(auth)
pvt_dengue_sensors(auth)
fluview(..., auth)
pvt_ght(auth, ...)
pvt_meta_afhsb(auth)
pvt_meta_norostat(auth)
pvt_norostat(auth)
pvt_quidel(auth)
pvt_sensors(auth, ...)
pvt_twitter(auth, ...)
```
- [ ] Streaming mode support
        - Not implemented. API requests made with [`httr::retry`](https://httr.r-lib.org/reference/RETRY.html)
- [ ] Apply shifts (lags/leads) to a signal
	- Not implemented, possibly out of scope (data processing/wrangling).
- [ ] Plot choropleths for a signal
	- Not implemented, possibly out of scope (data plotting).
- [ ] Add shape data to signal dataframe.
	- Don't know what this means.
- [x] Allow changing endpoint to staging server
```r
r$> epicall <- covidcast("fb-survey", "smoothed_cli", "day", "nation", epirange(20210405, 20210410), "us")
r$> epicall %>% with_base_url("https://staging.delphi.cmu.edu/epidata/") %>% fetch_df
```
- [ ] Append new data given locally stored data
	- Not implemented, possibly out of scope (data processing/wrangling).
- [ ] Select earliest and latest issue for each observation in a signal
	- Doesn't appear to be implemented.
- [ ] Convert arbitrary dataframe to signal format
	- Don't know what this means.
- [ ] Asynchronous calls
	- Not implemented.
- [ ] Correlate two returned signal dataframes together
	- Not implemented, possibly out of scope (data processing/wrangling).
- [ ] Pivot a list of dataframes “wide” or "long"
	- Not implemented, possibly out of scope (data processing/wrangling). 
- [ ] Pivot a list of dataframes “long”
	- Not implemented, possibly out of scope (data processing/wrangling).
- [ ] Optimized call batching
	- Not implemented.
- [ ] Included population data for msa, county, state
	- Not implemented.
- [ ] CoffeeScript and JS support
	- Not implemented.
- [ ] Request multiple dataframes at once
	- Don't know what this means.
- [ ] Plot bubble maps for a signal
	- Not implemented, possibly out of scope (data plotting).
- [ ] Convert geo abbreviations to/from names to/from codes
	- Not implemented.
- [ ] Animate a signal over time
	- Not implemented, possibly out of scope (data plotting).

**Comment by krivard** [comment] 2022-03-21 16:41
Piecewise clarifications:

> Add shape data to signal dataframe

this is more plotting

> Streaming mode support / `httr:retry`

This is probably meant more in the sense of "can we begin processing the first few rows returned before the complete dataset has finished downloading" - which may be difficult/impossible in R?

> Convert arbitrary dataframe to signal format

This is to support researchers who want to compare an epidata dataset with a custom one -- a function to, given some arbitrary data frame and a column mapping, produce a data frame in epidata format. Really only makes sense if we provide data plotting/processing/wrangling utilities as well.

> Request multiple dataframes at once

this is either multiple signals at once (which should be possible for covidcast) or multiple epidata data frames at once (which may be in wildly different formats); the latter is probably difficult but useful.

**Comment by dshemetov** [comment] 2022-03-22 06:40
> ```r
> separate handling for `as_of` and `issue`...
> ```
It looks like specifying both is possible and not much validation is done. In the case below, the package delegates the decision to the API and the API has `issues` take precedence over `as_of`. 
```r
r$> epicall <- covidcast("jhu-csse", "deaths_incidence_prop", "day", "nation", epirange(20211001, 20211010), "us", issues = epirange(20211001, 20211020), as_of = 20211030)
r$> epicall %>% request_url
"https://delphi.cmu.edu/epidata//covidcast/?data_source=jhu-csse&signals=deaths_incidence_prop&time_type=day&geo_type=nation&time_values=20211001-20211010&geo_values=us&as_of=20211020&issues=20210901-20210910"
```

It also looks like the API doesn't accept `as_of` ranges? Hitting [this](https://delphi.cmu.edu/epidata//covidcast/?data_source=jhu-csse&signals=confirmed_incidence_prop&time_type=day&geo_type=nation&time_values=20210901-20210930&geo_values=us&as_of=20210901-20211230) request produces `as_of=latest` data, it seems.

**Comment by dshemetov** [comment] 2022-03-22 06:43
@brookslogan any chance you know about R packages that allow streaming downloading / reading of CSV/JSON files? Probably not high priority or requiring a deep search.

**Comment by dshemetov** [comment] 2022-03-22 06:48
> this is either multiple signals at once ...
Current implementation can do multiple signals at once. A user can combine a few `covidcast` calls with bind_rows to get multiple data sources and epidata dataframes together in a single object.

**Comment by ryantibs** [comment] 2022-03-22 10:22
Thanks for diving in Dmitry!

Now that the other packages are taking shape (e.g., `epiprocess`, `epipredict`, and soon a geo aggregation package) I think it's become even more clear that we should consider data wrangling & plotting out of scope. So if `delphi.epidata` "just gives you data" then this seems like a perfectly good scope and will allow us to finish more quickly.

Misc comments:
- No range for `as_of`, only for `issue`: that makes sense to me
- Agree with Katie that converting outside data to given signal format not important given that we don't provide wrangling or plotting tools. 
- Just to be clear we aren't defining a single signal format here, right? There's no unified class or structure, each endpoint could conceivably give you back something different in format?)

Lastly, what would really help me to see how the package is shaping up, and help me see what decisions need to be made (if any), would be to have you flesh out the vignettes & documentation. Feel free to re-think what the structure of the vignettes is---think from the perspective of how best to teach a user about the array of offerings. It would be nice to have some significant examples from the FluView endpoint; and/or the vignettes can recreate examples from the blog posts Katie pointed out at the beginning of this issue.

**Comment by dshemetov** [comment] 2022-03-22 22:46
Right, no signal format definitions here - just downloading a JSON file and then using a reader to convert it to common types (csv, data.frame, tibble). 👍 on keeping this package minimal and just "get data".

Will take a look at the blog posts, vignettes, and see what I can do.

**Comment by brookslogan** [comment] 2022-03-23 17:17
Regarding downloading mechanism:
- I haven't tried any streaming libraries.  The most promising from a very short search is sparklyr, which also has functions that seem relevant (or duplicative?) to epiprocess and epipredict.  But I'm not sure we would want to just use pre-packaged streaming, because we have I don't think we have guarantees about ordering of API response rows across all API endpoints + because of versioning.
- It's still worth taking a look at sparklyr for epiprocess and epipredict.  (And maybe arrow as well?  Although I recall arrow causing some installation problems/waits.)
- I think delphi.epidata currently uses csv as the transfer mechanism for most/all output formats.

**Comment by brookslogan** [comment] 2022-03-25 19:43
Looks like Spark doesn't support streaming from https, so sparklyr is out for streaming support unless we have a clever way to implement a supported protocol without too much implementation hassle.  (Plus, the Spark setup is frustrating.)  Might still be worth looking at if it's really great at the stuff we're trying to do in epiprocess.

I'm not convinced our data isn't potentially medium/large --- think issues & counties.  But if it's not, then we don't need streaming.  If it's only medium, then we can do streaming ourselves via chunking the download.  We may be forced to use chunking anyway because we don't have uniform guarantees about the order of results from the API endpoints.

I would think the following are higher priority than trying to implement streaming:
- Tools to cache and perform smart updates on the cache.
- Speeding up download processing via #6 or similar.
- Optimizing cache format.  (Is cache a collection of RDS files?  How are they divided up?  Is "cache" actually a database? ...)

And I'm not sure how high a priority the above are... I remember being pleased with how fast archive data downloads went with delphi.epidata when I tested it.

**Comment by krivard** [comment] 2022-03-28 14:45
Re:size of data:  

For reference, a JHU dataset as-of 2021-10-13 for all signals and geos between 2020-01-22 and 2021-09-26 (613 days) is ~1GB in submission CSV format, uncompressed. JHU updates each day's figures ~20x on average, so anyone needing the complete version history (instead of just the most recent version <= 2021-10-13) would need to pull down at least ~20GB of data. API response CSVs could be ~4x that if they include the signal, geo type, time type, time value, and issue columns, which submission CSVs don't have.

so it's not terabytes, but it's still pretty nontrivial. The good news is that JHU is the worst-case scenario -- every county in the USA is represented _and_ there's lots of versioning; the next worst (CHNG, HSP, Quidel) have lots of versioning but don't hit every county. The bad news is that JHU is used by literally everyone, so it's in our best interest to optimize its performance.

**Comment by dshemetov** [comment] 2022-03-28 17:24
Point taken on that use case. We do have query row limits at this point, so the user would need to batch those 20GB calls down (just pulling the latest full history issue would be 3000 counties x 600 days = 1.8 * 10e5 rows vs 10e6 row limit).

**Comment by dsweber2** [comment] 2023-07-20 23:05
Dmitry and I went back through and made new issues for the remaining PRD docs.

**Closed by dsweber2** 2023-07-20 23:05 UTC
Labels: P3
